# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0939c96def808e41bcfc4552a006bd306979d5e4371b1740f911d36a86cdab23c21b7d4fb5711ceb3013c6be3cbbc6617c3314fdb0eff3c0807258cb43ffa5ae

test:
  secret_key_base: 289a7e90363a1a9dbbe56d148ea9d67f94590655f95f7b61c802629e81e21670614487b8a7892c0bde61f06f0911b402a69e289b80fb3bd30ae2267536f86d8f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
